<a href="https://colab.research.google.com/github/Nivedhasriram/FeaturesEngineering-ML-/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Question-1

In [ ]:
# 1xn dimensional array
N=5
vector = np.random.rand(N)

In [ ]:
# mean and variance
mean = np.mean(vector)
variance = np.var(vector)

In [ ]:
print("Vector array:",vector)
print("Mean:",mean)
print("Variance:",variance)

Vector array: [0.9974483  0.49347296 0.37067872 0.33278602 0.84218849]
Mean: 0.6073148993124154
Variance: 0.07033848916085257


In [ ]:
# Question-2

In [ ]:
# 2 1xM dimensional arrays
M= 10
vector1 = np.random.rand(M)
vector2 = np.random.rand(M)

In [ ]:
# Covariance matrix and value between vectors
covariance_matrix = np.cov(vector1,vector2)
covariance = covariance_matrix[0,1]

In [ ]:
print("Vector 1 array:",vector1)
print("Vector 2 array:",vector2)
print("Covariance:",covariance)

Vector 1 array: [0.4001783  0.58551241 0.63208769 0.39471779 0.91925017 0.27608009
 0.12310425 0.18645639 0.13915361 0.84677417]
Vector 2 array: [0.55692595 0.3473794  0.01027561 0.59002165 0.46793497 0.3721214
 0.72366781 0.65321594 0.59076582 0.14365911]
Covariance: -0.04370992062534783


In [ ]:
# Question-3

In [ ]:
# 2 1xR dimensional arrays
R = 8
vector1 = np.random.rand(R)
vector2 = np.random.rand(R)

In [ ]:
# Correlation coefficient matrix
correlation_matrix = np.corrcoef(vector1,vector2)
correlation = correlation_matrix[0,1]

In [ ]:
print("Vector 1 array:",vector1)
print("Vector 2 array:",vector2)
print("Correlation:",correlation)

Vector 1 array: [0.05168636 0.64013497 0.4384771  0.05930548 0.37650686 0.31142206
 0.47100263 0.89398075]
Vector 2 array: [0.95877379 0.74464921 0.28454452 0.06265504 0.33793405 0.16046642
 0.17447797 0.44481961]
Correlation: 0.04523049558769619


In [ ]:
# Question-4

In [ ]:
# LxQ dimensional matrix
L = 5
Q = 10
matrix = np.random.rand(L,Q)

In [ ]:
# Covariance and coreelation matrix
covariance_matrix = np.cov(matrix)
correlation_matrix = np.corrcoef(matrix)

In [ ]:
print("Matrix (Features x Samples):",matrix)
print("Covariance matrix:",covariance_matrix)
print("Correlation matrix:",correlation_matrix)

Matrix (Features x Samples): [[0.02090518 0.3039448  0.14827895 0.00156469 0.60466141 0.96286451
  0.47067242 0.43376399 0.44584559 0.27633844]
 [0.61521392 0.65622093 0.51718979 0.75448386 0.10312666 0.54379269
  0.01445546 0.10771518 0.31581177 0.16975395]
 [0.86338479 0.38738406 0.52776273 0.00972911 0.28486454 0.93233635
  0.75273744 0.77904265 0.23622962 0.07326399]
 [0.26491764 0.43478884 0.76511447 0.71063632 0.66757126 0.43726132
  0.91923514 0.51730533 0.07631287 0.64183461]
 [0.30683652 0.49554156 0.87077127 0.60790842 0.30881991 0.279373
  0.2559205  0.14295225 0.59007929 0.40763385]]
Covariance matrix: [[ 0.08292426 -0.03066211  0.03595727 -0.00540464 -0.02933844]
 [-0.03066211  0.0722505  -0.00631048 -0.01946854  0.02903549]
 [ 0.03595727 -0.00631048  0.11223729 -0.00760918 -0.03594142]
 [-0.00540464 -0.01946854 -0.00760918  0.06255007  0.00229941]
 [-0.02933844  0.02903549 -0.03594142  0.00229941  0.04683086]]
Correlation matrix: [[ 1.         -0.39613274  0.37271544 -0.0